language: ruby
rvm:
- '2.3.1'
sudo: false
cache: bundler
env:
  global:
  - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
  - RUBY_GC_HEAP_INIT_SLOTS=600000
  - RUBY_GC_HEAP_GROWTH_FACTOR=1.25
addons:
  postgresql: '9.4'
before_install: bin/setup
script:
- bundle exec bin/rails app:test:providers:vmware:setup app:test:providers:vmware
after_script: bundle exec codeclimate-test-reporter
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/e8962e1c2f26da9bc7d4
    on_success: change
    on_failure: always
    on_start: never
