---
config.storageDevice.hostBusAdapter:
- !ruby/object:RbVmomi::VIM::HostBlockHba
  props:
    :key: key-vim.host.BlockHba-vmhba0
    :device: vmhba0
    :bus: 0
    :status: unknown
    :model: 631xESB/632xESB IDE Controller
    :driver: ata_piix
    :pci: 00:1f.1
- !ruby/object:RbVmomi::VIM::HostBlockHba
  props:
    :key: key-vim.host.BlockHba-vmhba1
    :device: vmhba1
    :bus: 14
    :status: unknown
    :model: Smart Array P400
    :driver: cciss
    :pci: 0e:00.0
- !ruby/object:RbVmomi::VIM::HostBlockHba
  props:
    :key: key-vim.host.BlockHba-vmhba32
    :device: vmhba32
    :bus: 0
    :status: unknown
    :model: 631xESB/632xESB IDE Controller
    :driver: ata_piix
    :pci: 00:1f.1
config.storageDevice.scsiLun:
- !ruby/object:RbVmomi::VIM::ScsiLun
  props:
    :deviceName: "/vmfs/devices/genscsi/mpx.vmhba0:C0:T0:L0"
    :deviceType: cdrom
    :key: key-vim.host.ScsiLun-0005000000766d686261303a303a30
    :uuid: 0005000000766d686261303a303a30
    :descriptor:
    - !ruby/object:RbVmomi::VIM::ScsiLunDescriptor
      props:
        :quality: lowQuality
        :id: mpx.vmhba0:C0:T0:L0
    - !ruby/object:RbVmomi::VIM::ScsiLunDescriptor
      props:
        :quality: lowQuality
        :id: vml.0005000000766d686261303a303a30
    - !ruby/object:RbVmomi::VIM::ScsiLunDescriptor
      props:
        :quality: lowQuality
        :id: 0005000000766d686261303a303a30
    :canonicalName: mpx.vmhba0:C0:T0:L0
    :displayName: Local HL-DT-ST CD-ROM (mpx.vmhba0:C0:T0:L0)
    :lunType: cdrom
    :vendor: HL-DT-ST
    :model: DVD-ROM GDR-D10N
    :revision: '3.00'
    :scsiLevel: 5
    :serialNumber: unavailable
    :alternateName: []
    :standardInquiry:
    - 5
    - -128
    - 5
    - 50
    - 91
    - 0
    - 0
    - 0
    - 72
    - 76
    - 45
    - 68
    - 84
    - 45
    - 83
    - 84
    - 68
    - 86
    - 68
    - 45
    - 82
    - 79
    - 77
    - 32
    - 71
    - 68
    - 82
    - 45
    - 68
    - 49
    - 48
    - 78
    - 51
    - 46
    - 48
    - 48
    - 65
    - 66
    - 67
    - 66
    - 65
    - 32
    - 32
    - 32
    - 48
    - 54
    - 47
    - 49
    - 50
    - 47
    - 49
    - 57
    - 32
    - 32
    - 32
    - 32
    - 1
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 1
    - 1
    - 1
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 16
    - 17
    - 16
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 16
    - 16
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 16
    - 0
    - 0
    - 0
    - 0
    - 1
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    :operationalState:
    - ok
    :capabilities: !ruby/object:RbVmomi::VIM::ScsiLunCapabilities
      props:
        :updateDisplayNameSupported: true
- !ruby/object:RbVmomi::VIM::HostScsiDisk
  props:
    :deviceName: "/vmfs/devices/disks/mpx.vmhba1:C0:T0:L0"
    :deviceType: disk
    :key: key-vim.host.ScsiDisk-0000000000766d686261313a303a30
    :uuid: 0000000000766d686261313a303a30
    :descriptor:
    - !ruby/object:RbVmomi::VIM::ScsiLunDescriptor
      props:
        :quality: lowQuality
        :id: mpx.vmhba1:C0:T0:L0
    - !ruby/object:RbVmomi::VIM::ScsiLunDescriptor
      props:
        :quality: lowQuality
        :id: vml.0000000000766d686261313a303a30
    - !ruby/object:RbVmomi::VIM::ScsiLunDescriptor
      props:
        :quality: lowQuality
        :id: 0000000000766d686261313a303a30
    :canonicalName: mpx.vmhba1:C0:T0:L0
    :displayName: Local VMware Disk (mpx.vmhba1:C0:T0:L0)
    :lunType: disk
    :vendor: 'VMware  '
    :model: 'Block device    '
    :revision: '1.0 '
    :scsiLevel: 2
    :serialNumber: unavailable
    :alternateName: []
    :standardInquiry:
    - 0
    - 0
    - 2
    - 0
    - 32
    - 0
    - 0
    - 115
    - 86
    - 77
    - 119
    - 97
    - 114
    - 101
    - 32
    - 32
    - 66
    - 108
    - 111
    - 99
    - 107
    - 32
    - 100
    - 101
    - 118
    - 105
    - 99
    - 101
    - 32
    - 32
    - 32
    - 32
    - 49
    - 46
    - 48
    - 32
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    :operationalState:
    - ok
    :capabilities: !ruby/object:RbVmomi::VIM::ScsiLunCapabilities
      props:
        :updateDisplayNameSupported: true
    :capacity: !ruby/object:RbVmomi::VIM::HostDiskDimensionsLba
      props:
        :blockSize: 512
        :block: 1146734896
    :devicePath: "/vmfs/devices/disks/mpx.vmhba1:C0:T0:L0"
    :physicalLocation: []
config.storageDevice.scsiTopology.adapter:
- !ruby/object:RbVmomi::VIM::HostScsiTopologyInterface
  props:
    :key: key-vim.host.ScsiTopology.Interface-vmhba0
    :adapter: key-vim.host.BlockHba-vmhba0
    :target:
    - !ruby/object:RbVmomi::VIM::HostScsiTopologyTarget
      props:
        :key: key-vim.host.ScsiTopology.Target-vmhba0:0
        :target: 0
        :lun:
        - !ruby/object:RbVmomi::VIM::HostScsiTopologyLun
          props:
            :key: key-vim.host.ScsiTopology.Lun-0005000000766d686261303a303a30
            :lun: 0
            :scsiLun: key-vim.host.ScsiLun-0005000000766d686261303a303a30
        :transport: !ruby/object:RbVmomi::VIM::HostBlockAdapterTargetTransport
          props: {}
- !ruby/object:RbVmomi::VIM::HostScsiTopologyInterface
  props:
    :key: key-vim.host.ScsiTopology.Interface-vmhba1
    :adapter: key-vim.host.BlockHba-vmhba1
    :target:
    - !ruby/object:RbVmomi::VIM::HostScsiTopologyTarget
      props:
        :key: key-vim.host.ScsiTopology.Target-vmhba1:0
        :target: 0
        :lun:
        - !ruby/object:RbVmomi::VIM::HostScsiTopologyLun
          props:
            :key: key-vim.host.ScsiTopology.Lun-0000000000766d686261313a303a30
            :lun: 0
            :scsiLun: key-vim.host.ScsiDisk-0000000000766d686261313a303a30
        :transport: !ruby/object:RbVmomi::VIM::HostBlockAdapterTargetTransport
          props: {}
- !ruby/object:RbVmomi::VIM::HostScsiTopologyInterface
  props:
    :key: key-vim.host.ScsiTopology.Interface-vmhba32
    :adapter: key-vim.host.BlockHba-vmhba32
    :target: []
